eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: metadata-service
          uri: lb://metadata-service
          predicates:
            - Path=/metadata/**
          filters:
            - RewritePath=/metadata/(?<path>.*), /$\{path}
        - id: images-service
          uri: lb://images-service
          predicates:
            - Path=/images/**
          filters:
            - RewritePath=/images/(?<path>.*), /$\{path}