eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

zuul:
  routes:
    images-service:
      path: /images/**
      service-id: IMAGES-SERVICE
    user-service:
      path: /user/**
      service-id: USER-SERVICE
    metadata-service:
      path: /metadata/**
      service-id: METADATA-SERVICE

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
