eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

zuul:
#  ignored-services: *
  routes:
    images-service:
      path: /images/**
      service-id: IMAGES-SERVICE
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: false
      sensitive-headers: Cookie, Set-Cookie

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
