eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

zuul:
#  ignored-services: *
  routes:
    images-service:
      path: /images/**
      service-id: IMAGES-SERVICE
    user-service:
      path: /user/**
      service-id: USER-SERVICE

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000
