
server:
  port: 4000

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8282/eureka
    register-with-eureka: true
  instance:
    preferIpAddress: true

zuul:
  routes:
    metadata:
      path: /metadata/**
      url: http://localhost:8181